### PR TITLE
move bitcore-lib to peer dependency

### PR DESCRIPTION
**Pull request by Firescar96**
an alternative to this pull request:
https://github.com/bitpay/bitcore-lib/pull/187

### CODE REVIEW

**Comment by Firescar96** [comment]
bitcore-lib is no longer a dependency so the test suite does not import it and crashes. The other tests pass though.

**Comment by Firescar96** [comment]
I just noticed this PR, which has since gone stale
https://github.com/bitpay/bitcore-mnemonic/pull/26

**Comment by Firescar96** [comment]
@matiu do you have any comments?

**Comment by bahi-2** [comment]
Hmm.. hello. This is not solved in this branch also. The problem is very silly.In your versionGuard function you compare a variable version with undefined, and it always enters into error state because version is an initialized string. Even if this was not so, with require('./package.json').version; you would get the version of the persons project, and not a response to a question whether there are multiple versions installed. 
bitcore.version = 'v' + require('./package.json').version;
bitcore.versionGuard = function(version) {
  if (version !== undefined) {
    var message = 'More than one instance of bitcore-lib found. ' +
      'Please make sure to require bitcore-lib and check that submodules do' +
      ' not also include their own bitcore-lib dependency.';
    throw new Error(message);
  }
};

**Comment by Firescar96** [comment]
Bump @matiu

**Comment by Firescar96** [comment]
Bump @kleetus @nitsujlangston

**Comment by tab00** [comment]
What is the status of this? I've just got the "More than one instance of bitcore-lib found" error.

**Comment by JamesJansson** [comment]
Bumping here in June. Anyone listening? This makes the explorer unusable.

**Comment by taylorjdawson** [comment]
Can't use `bitcore-lib` with `bitcore-ecies` without getting `Error: More than one instance of bitcore-lib found.` Please for the love of everything that is good and holy merge this request. Thank you.

**Comment by Firescar96** [comment]
Paging Agent @cmgustavo, Agent @Gamboster, Agent @gabrielbazan7, Agent @rastajpa, Agent @micahriggan, Agent @matiu, and Agent @ryanxcharles. Your assistance is needed.

**Comment by Firescar96** [comment]
And Stallman looked down from on high, from upon a tower of lisp machines and stacks of Thinkpad T400s. And smiled, for the world below so moved him. The power of free software prevailed once again. For on git, no pull request can be forgotten and by the power of all that is GNU all contributions are welcome.

**Pull request merged**
