### PR TITLE
Add JA test vectors

### PR DESCRIPTION
**Pull request by dabura667**
(Note: changed this PR to only contain JP test vectors)

This will add Japanese test vectors to the library.

### CODE REVIEW

**Comment by dabura667** [comment]
Note: this PR requires #39 which is why it is failing.

**Comment by braydonf** [comment]
These vectors I believe originally came from: https://github.com/trezor/python-mnemonic/blob/master/vectors.json It may be useful to follow up upstream as well?

**Comment by dabura667** [comment]
Yes, I created these using python by replacing existing code with Japanese (rather than adding supprt for multiple languages. Then I ran those tests manually against my own javascript implementation based off early versions of bip39 (bitcoinjs-lib), but again, no upstream support.

I just added Japanese in a pr to bip39 the other day.

I should also add the vectors to python-mnemonic.

**Comment by braydonf** [comment]
How did you produce the seed hex values?

Did you run  `python3 generate_vectors.py` from https://github.com/trezor/python-mnemonic

**Comment by dabura667** [comment]
I believe I just used the same as English.

**Comment by braydonf** [comment]
I was running https://github.com/bitpay/bitcore-mnemonic/pull/39 with vectors generated from `python3 generate_vectors.py`. Even though the vectors committed in the python-mnemonic repository only include English vectors, the script will also generate Japanese, and was able to get it to work with a few modifications. However I needed to replace the ideographic spaces that was generated with `0xe38080`, and wasn't able to verify that the `toSeed()` hex strings.

**Comment by dabura667** [comment]
@braydonf thats because the generate_vectors uses passphrase TREZOR whereas mine use a japanese passphrase

**Comment by braydonf** [comment]
I tried using that one as well, and didn't have any luck.

**Comment by dabura667** [comment]
@braydonf I just tried again, and suddenly forgot how to get python to cooperate with UTF-8...

I struggled for a while, and decided to quit. However, the vectors I have here I have verified against the python reference implementation... though I forget how I did it.

I even tried using a VM with Ubuntu, still was getting ASCII errors crying about \u3000...

**Comment by braydonf** [comment]
I used python3, and the `generate_vectors.py` worked (except for the ideographic space issues mentioned earlier), I had issues when trying to use python2.7.

**Pull request merged**
